stages:
  - build
  - test
  - deploy
  - mobile-build

build:
  stage: build
  image: golang:latest
  script:
    - cd backend
    - go get -d -v
    - go build -o hehe -v .

test:
  stage: test
  image: golang:latest
  services:  
    - postgres:12.2-alpine
  variables:
    POSTGRES_DB: testingdb
    POSTGRES_USER: pege
    POSTGRES_PASSWORD: asfd1234
    POSTGRES_HOST_AUTH_METHOD: trust
  script:
    - cd backend
    - go get -d -v
    - export LF=Y
    - export DBUSN=pege
    - export DBPASS=asfd1234
    - export DBHOST=postgres
    - export DBPORT=5432
    - export DBNAME=testingdb
    - export ISTEST=1
    - go test cakrawala.id/m/test

deploy:
  stage: deploy
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $VM_IPADDRESS >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh g13519028@$VM_IPADDRESS "ls"

# mobile:
#   stage: mobile-build
#   image: "cirrusci/flutter:1.22.5"
#   script:
#     - cd mobile
#     - flutter packages get
#     - flutter doctor
#     - flutter build apk